{
	"version": 1654049849,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/背景.png",
		"images/ak47-sheet0.png",
		"images/砲彈-sheet0.png",
		"images/block-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/m4a1-sheet0.png",
		"images/牆-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/wrong sound effect.ogg",
		"media/“i’m gonna come” sound effect.ogg",
		"media/“the chinese virus” sound effect.ogg",
		"media/havana ( cover by donald trump ).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}